/*
{
        brand: "",
        material: "",
        type: "",
        coating: "",
        misc: "",
        "misc type": "",
        "sphere max": "",
        "sphere min": "",
        "cyl max": "",
        img: "",
    },
*/
import { Request, Response } from 'express';
const express = require('express');
const router = express.Router();

const lenses = [
    {
        brand: "Somo",
        material: "plastic",
        type: "spheric",
        coating: null,
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -6.00,
        "cyl max": 2.00,
        img: "",
    },
    {
        brand: "Somo",
        material: "plastic",
        type: "spheric",
        coating: "Ultraclear",
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -6.00,
        "cyl max": -2.00,
        img: "",
    },
    {
        brand: "Somo",
        material: "polycarbonate",
        type: "spheric",
        coating: null,
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -8.00,
        "cyl max": -2.00,
        img: "",
    },
    {
        brand: "Somo",
        material: "polycarbonate",
        type: "spheric",
        coating: null,
        misc: "Transitions Xtractive Grey",
        "misc type": "xtractive",
        "sphere max": 4.00,
        "sphere min": -8.00,
        "cyl max": -2.00,
        img: "",
    },
    {
        brand: "Somo",
        material: "polycarbonate",
        type: "spheric",
        coating: "Ultraclear",
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -8.00,
        "cyl max": -2.00,
        img: "",
    },
    {
        brand: "Somo",
        material: "polycarbonate",
        type: "aspheric",
        coating: "Ultraclear",
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -10.00,
        "cyl max": -3.00,
        img: "",
    },
    {
        brand: "Somo",
        material: "polycarbonate",
        type: "spheric",
        coating: "Ultraclear",
        misc: "Transitions Grey",
        "misc type": "transitions",
        "sphere max": 4.00,
        "sphere min": -8.00,
        "cyl max": -2.00,
        img: "",
    },
    {
        brand: "Somo",
        material: "polycarbonate",
        type: "spheric",
        coating: "Ultraclear",
        misc: "Transitions Brown",
        "misc type": "transitions",
        "sphere max": 4.00,
        "sphere min": -8.00,
        "cyl max": -2.00,
        img: "",
    },
    {
        brand: "Somo",
        material: "Trivex",
        type: "spheric",
        coating: null,
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -8.00,
        "cyl max": -2.00,
        img: "",
    },
    {
        brand: "Somo",
        material: "Trivex",
        type: "spheric",
        coating: "Ultraclear",
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -8.00,
        "cyl max": -2.00,
        img: "",
    },
    {
        brand: "Somo",
        material: "1.67",
        type: "spheric",
        coating: null,
        misc: null,
        "misc type": null,
        "sphere max": 3.00,
        "sphere min": -13.00,
        "cyl max": -2.00,
        img: "",
    },
    {
        brand: "Somo",
        material: "1.67",
        type: "spheric",
        coating: "Ultraclear",
        misc: null,
        "misc type": null,
        "sphere max": 3.00,
        "sphere min": -13.00,
        "cyl max": -2.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "plastic",
        type: "spheric",
        coating: null,
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -9.00,
        "cyl max": -3.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "plastic",
        type: "spheric",
        coating: null,
        misc: "Transitions Grey",
        "misc type": "transitions",
        "sphere max": 4.00,
        "sphere min": -9.00,
        "cyl max": -3.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "plastic",
        type: "spheric",
        coating: null,
        misc: "Transitions Brown",
        "misc type": "transitions",
        "sphere max": 4.00,
        "sphere min": -9.00,
        "cyl max": -3.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "plastic",
        type: "spheric",
        coating: "Coral+",
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -9.00,
        "cyl max": -3.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "plastic",
        type: "spheric",
        coating: "Coral+",
        misc: "Transitions Grey",
        "misc type": "transitions",
        "sphere max": 4.00,
        "sphere min": -9.00,
        "cyl max": -3.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "plastic",
        type: "spheric",
        coating: "Coral+",
        misc: "Transitions Brown",
        "misc type": "transitions",
        "sphere max": 4.00,
        "sphere min": -9.00,
        "cyl max": -3.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "polycarbonate",
        type: "spheric",
        coating: null,
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -11.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "polycarbonate",
        type: "spheric",
        coating: null,
        misc: "Transitions Grey",
        "misc type": "transitions",
        "sphere max": 4.00,
        "sphere min": -11.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "polycarbonate",
        type: "spheric",
        coating: null,
        misc: "Transitions Brown",
        "misc type": "transitions",
        "sphere max": 4.00,
        "sphere min": -11.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "polycarbonate",
        type: "spheric",
        coating: null,
        misc: "Transitions Xtractive Grey",
        "misc type": "xtractive",
        "sphere max": 4.00,
        "sphere min": -11.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "polycarbonate",
        type: "spheric",
        coating: "Coral+",
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -11.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "polycarbonate",
        type: "spheric",
        coating: "Coral+",
        misc: "Transitions Grey",
        "misc type": "transitions",
        "sphere max": 4.00,
        "sphere min": -11.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "polycarbonate",
        type: "spheric",
        coating: "Coral+",
        misc: "Transitions Brown",
        "misc type": "transitions",
        "sphere max": 4.00,
        "sphere min": -11.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "polycarbonate",
        type: "aspheric",
        coating: "Coral+",
        misc: "Coral+ Blue Blocker",
        "misc type": "blue block",
        "sphere max": 6.00,
        "sphere min": -15.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "polycarbonate",
        type: "aspheric",
        coating: "Coral+",
        misc: null,
        "misc type": null,
        "sphere max": 6.00,
        "sphere min": -15.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "polycarbonate",
        type: "aspheric",
        coating: "Coral+",
        misc: "Transitions Grey",
        "misc type": "transitions",
        "sphere max": 6.00,
        "sphere min": -15.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "polycarbonate",
        type: "aspheric",
        coating: "Coral+",
        misc: "Transitions Brown",
        "misc type": "transitions",
        "sphere max": 6.00,
        "sphere min": -15.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "1.67",
        type: "spheric",
        coating: null,
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -16.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "1.67",
        type: "spheric",
        coating: "Coral+",
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -16.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "1.67",
        type: "spheric",
        coating: null,
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -16.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "1.67",
        type: "spheric",
        coating: "Coral+",
        misc: "Transitions Grey",
        "misc type": "transitions",
        "sphere max": 4.00,
        "sphere min": -16.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "1.67",
        type: "spheric",
        coating: "Coral+",
        misc: "Transitions Brown",
        "misc type": "transitions",
        "sphere max": 4.00,
        "sphere min": -16.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "1.74",
        type: "spheric",
        coating: null,
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -16.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "1.74",
        type: "spheric",
        coating: "Coral+",
        misc: null,
        "misc type": null,
        "sphere max": 4.00,
        "sphere min": -16.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "1.74",
        type: "spheric",
        coating: "Coral+",
        misc: "Transitions Grey",
        "misc type": "transitions",
        "sphere max": 4.00,
        "sphere min": -16.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "1.74",
        type: "spheric",
        coating: "Coral+",
        misc: "Transitions Brown",
        "misc type": "transitions",
        "sphere max": 4.00,
        "sphere min": -16.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Shore",
        material: "1.74",
        type: "spheric",
        coating: "Coral+",
        misc: "Coral+ Blue Blocker",
        "misc type": "blue block",
        "sphere max": 4.00,
        "sphere min": -16.00,
        "cyl max": -4.00,
        img: "",
    },
    {
        brand: "Conant",
        material: "hivex",
        type: "spheric",
        coating: null,
        misc: "Blue Blocker",
        "misc type": "blue block",
        "sphere max": 6.00,
        "sphere min": -10.00,
        "cyl max": -4.00,
        img: "",
    },
];

router.get("/", (req: Request, res: Response) => {
    const { material, type, coating, misc } = req.query;
    console.log(`request received: ${req.query}`);
})

export default router;